#!/bin/bash

date_formatted=$(date +%Y%m%d)
# maybe the file should be kept in ~/.mathlog !!!!! there's no reason for
# the user to actually see it, right?
pathname=$HOME/Math/mathlog 
# in that case, the pathname should just be $HOME/.mathlog
# first check to make sure .mathlog is not a folder. throw an error in that case


function updateMaster {
    sect_name=$(date -d$date_formatted +%B\ %d,\ %Y) || exit 1
    sed -i "s|\%\%\%|\n\\\section{$sect_name}\n\\\input{$pathname/$date_formatted.tex}\n\%\%\%|g" "$pathname/mathlog.tex"
    # to change: use absolute filepath. sed is begin finnicky however.
    # btw: do NOT use commas as a separator in this sed command. It broke everything
    # and I haven't a clue why
}

if [ -e $pathname/'.TESTFILE' ]
then
    echo "Mathlog in use!"
    exit 1
fi

# if I'm hiding the directory from the user, I should probably have command
# that outputs the mathlog file's path, so you can pipe it to scp or whatever.
# also, instead of evince or vim, use the program listed in your system defaults
while getopts ":m:vd:c" opt; do
    case $opt in 
        d) date_formatted=$OPTARG ;;
        # set the date of your journal entry to a given date.
        # date needs to be given in YYYYMMDD format!
        v) evince ~/Math/mathlog/mathlog.pdf &
            exit 0 ;;
            # view the pdf
        m) if [ ! -e $pathname/$date_formatted'.tex' ]
        then
            updateMaster
        fi

        echo $OPTARG >> $pathname/$date_formated'.tex'
        exit 0 ;;
        # write a short journal entry without opening a text editor
        c) pdflatex -output-directory=$pathname mathlog.tex 
            exit 0 ;;
        # compiles
        \?)  echo "Invalid option -$OPTARG" >&2
            exit 1 ;;
    esac 
done 


if [ ! -e $pathname/$date_formatted'.tex' ]
then
    updateMaster
fi

echo "a" > $pathname/'.TESTFILE' # only make TESTFILE if I'm vimming

vim $pathname/$date_formatted'.tex'

rm $pathname/'.TESTFILE'
